In [7]:
import numpy as np
import or_gym
from or_gym.algos.knapsack.heuristics import *
from or_gym.algos.knapsack.math_prog import *
from or_gym.algos.math_prog_utils import *
import matplotlib.pyplot as plt
import pandas as pd
import time
%matplotlib inline

# Instantiate Unbounded Knapsack Model

Baseline model generates weights as random integers from $[1, 20]$ and values from $[0, 30]$.

In [2]:
env = or_gym.make('Knapsack-v0')

#### IP Model

In [3]:
model = build_ukp_ip_model(env)
model, results = solve_math_program(model)

print("IP Objective: {:.2f}".format(model.obj.expr()))
_ = [print("x_i = {:.0f}_{}".format(model.x[x].value, i)) 
     for i, x in enumerate(model.x) if model.x[x].value != 0]

IP Objective: 1151.00
x_i = 1_3
x_i = 1_6
x_i = 1_7
x_i = 1_10
x_i = 1_18
x_i = 1_19
x_i = 1_20
x_i = 1_21
x_i = 1_22
x_i = 1_23
x_i = 1_24
x_i = 1_26
x_i = 1_32
x_i = 1_34
x_i = 1_35
x_i = 1_38
x_i = 1_40
x_i = 1_43
x_i = 1_48
x_i = 1_50
x_i = 1_56
x_i = 1_60
x_i = 1_62
x_i = 1_63
x_i = 1_64
x_i = 1_66
x_i = 1_70
x_i = 1_73
x_i = 1_89
x_i = 1_90
x_i = 1_95
x_i = 1_97
x_i = 1_98
x_i = 1_102
x_i = 1_111
x_i = 1_118
x_i = 1_121
x_i = 1_122
x_i = 1_125
x_i = 1_128
x_i = 1_129
x_i = 1_130
x_i = 1_131
x_i = 1_132
x_i = 1_136
x_i = 1_139
x_i = 1_143
x_i = 1_147
x_i = 1_157
x_i = 1_164
x_i = 1_174
x_i = 1_176
x_i = 1_177
x_i = 1_180
x_i = 1_185
x_i = 1_187
x_i = 1_188
x_i = 1_189


In [4]:
heur_actions, heur_rewards = ukp_heuristic(env)
x_h = np.unique(heur_actions)
i_h = len(heur_actions)
print("Heuristic Objective: {:.2f}".format(sum(heur_rewards)))
print("x_i = {}_{}".format(i_h, x_h[0]))

Heuristic Objective: 5600.00
x_i = 200_188


In [5]:
# Get data from Beasley
url = 'http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/mdmkp_ct9.txt'
data = pd.read_csv(url)

In [6]:
data

15
0                                               500 30 
1     462 691 941 638 63 1000 39 84 520 425 982 642 ...
2     531 845 506 64 211 464 387 76 451 913 651 503 ...
3     729 702 263 408 480 453 392 737 75 557 818 858...
4     170 367 460 355 250 401 323 643 375 26 882 368...
...                                                 ...
1030  720 567 853 253 578 595 465 711 558 459 787 34...
1031  366 646 444 603 514 169 521 345 458 370 672 57...
1032  357 718 657 173 284 681 -426 494 315 282 82 12...
1033  -83 417 620 -59 -143 -67 -100 481 223 -115 374...
1034  283 -225 -9 -256 514 -213 502 -106 -97 -251 30...

[1035 rows x 1 columns]

In [9]:
env.item_numbers

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [43]:
weights, values, total_rewards = [], [], []
env = or_gym.make('Knapsack-v1')
count = 0
samples = 0
t0 = time.time()
while len(weights) < 5000:
    env.item_values = np.random.randint(0, 100, env.N)
    env.item_weights = np.random.randint(1, 100, env.N)
    env.item_limits_init = np.ones(env.N)
    env.reset()
    # Solve IP
    model = build_ukp_ip_model(env)
    model, results = solve_math_program(model)
    # Solve with Heuristic
    heur_actions, heur_rewards = bkp_heuristic(env)
    
    tot_h_rewards = sum(heur_rewards)
    samples += 1
    if tot_h_rewards != model.obj.expr():
        weights.append(env.item_weights.copy())
        values.append(env.item_values.copy())
        total_rewards.append((model.obj.expr(), tot_h_rewards))
        count += 1
        if count % 100 == 0 and count > 0:
            print("{} parameters found in {:.1f} seconds.".format(count, time.time() - t0))

100 parameters found in 4.3 seconds.
200 parameters found in 8.9 seconds.
300 parameters found in 13.8 seconds.
400 parameters found in 18.6 seconds.
500 parameters found in 23.6 seconds.
600 parameters found in 28.2 seconds.
700 parameters found in 32.6 seconds.
800 parameters found in 36.9 seconds.
900 parameters found in 41.5 seconds.
1000 parameters found in 45.7 seconds.
1100 parameters found in 50.8 seconds.
1200 parameters found in 55.4 seconds.
1300 parameters found in 60.0 seconds.
1400 parameters found in 65.0 seconds.
1500 parameters found in 69.3 seconds.
1600 parameters found in 74.2 seconds.
1700 parameters found in 79.5 seconds.
1800 parameters found in 85.3 seconds.
1900 parameters found in 90.2 seconds.
2000 parameters found in 95.1 seconds.
2100 parameters found in 99.8 seconds.
2200 parameters found in 104.7 seconds.
2300 parameters found in 110.6 seconds.
2400 parameters found in 115.1 seconds.
2500 parameters found in 120.2 seconds.
2600 parameters found in 125.4 s

In [44]:
r = np.vstack(total_rewards).T
assert sum(r[0]>r[1]) == count
m = (r[0] - r[1]).argmax()
print("Max diff = {:.2f}%, sample_n = {}".format((1 - r[1, m]/r[0, m])*100, m))
print("Non-optimal rate: {:.2f}%".format(count/samples*100))

Max diff = 3.59%, sample_n = 4166
Non-optimal rate: 64.33%


In [46]:
values[m]

array([18, 64, 79, 30, 79, 33, 69, 87, 17, 56, 95,  5, 88, 39, 18, 80, 59,
        9, 71, 80, 85, 44, 78, 88,  2, 40, 96, 99, 18, 99, 56, 64, 49, 90,
       18, 52, 44, 57, 60, 33,  3, 22, 14, 74, 11,  2, 23,  8, 90, 17, 44,
        0, 29, 80, 50,  9, 28, 19, 15, 32, 82, 98, 91, 41, 73, 35, 69,  3,
       80,  0, 35, 97, 26, 66, 47,  0, 21, 27, 66, 91, 54, 73, 79, 86, 63,
        3, 35, 60, 68, 33, 84, 40, 84, 46, 39, 15, 21, 98, 93, 92, 46, 49,
       26, 90, 44, 89, 34, 13, 52, 56, 24, 18, 77, 46, 98, 67, 66, 74, 40,
        5, 44, 49, 61, 54, 89, 87, 75, 58, 51, 22, 41, 54, 50, 93,  1, 17,
       93, 21, 52, 99, 94, 57, 90, 49, 58, 41, 16, 54, 60, 70, 71, 34, 37,
       43, 77, 89, 20, 40, 82, 17, 26, 92, 72, 44, 37,  2, 14, 45, 46, 31,
       18, 73, 28, 62, 33, 40, 18, 72, 13, 26, 44, 69, 47, 71, 65, 54, 71,
       92, 29, 96, 71, 72, 51, 82, 95, 87, 73, 79, 37, 51])

In [ ]:
# BKP
weights, values, limits, total_rewards = [], [], [], []
env = or_gym.make('Knapsack-v1')
count = 0
samples = 0
t0 = time.time()
while len(weights) < 5000:
    env.item_values = np.random.randint(0, 100, env.N)
    env.item_weights = np.random.randint(1, 100, env.N)
    env.item_limits_init = np.random.randint(0, 10, env.N)
    env.reset()
    # Solve IP
    model = build_bkp_ip_model(env)
    model, results = solve_math_program(model)
    # Solve with Heuristic
    heur_actions, heur_rewards = bkp_heuristic(env)
    
    tot_h_rewards = sum(heur_rewards)
    samples += 1
    if tot_h_rewards != model.obj.expr():
        weights.append(env.item_weights.copy())
        values.append(env.item_values.copy())
        limits.append(env.item_limits_init.copy())
        total_rewards.append((model.obj.expr(), tot_h_rewards))
        count += 1
        if count % 100 == 0 and count > 0:
            print("{} parameters found in {:.1f} seconds.".format(count, time.time() - t0))
            
r = np.vstack(total_rewards).T
assert sum(r[0]>r[1]) == count
m = (r[0] - r[1]).argmax()
print("Max diff = {:.2f}%, sample_n = {}".format((1 - r[1, m]/r[0, m])*100, m))
print("Non-optimal rate: {:.2f}%".format(count/samples*100))

100 parameters found in 6.9 seconds.
200 parameters found in 13.5 seconds.
300 parameters found in 20.4 seconds.
400 parameters found in 27.4 seconds.
500 parameters found in 34.5 seconds.
600 parameters found in 42.2 seconds.
700 parameters found in 49.0 seconds.
800 parameters found in 55.3 seconds.
900 parameters found in 62.5 seconds.
1000 parameters found in 70.9 seconds.
1100 parameters found in 78.6 seconds.
1200 parameters found in 86.3 seconds.
1300 parameters found in 92.8 seconds.
1400 parameters found in 100.1 seconds.
1500 parameters found in 106.9 seconds.
1600 parameters found in 114.5 seconds.
1700 parameters found in 121.8 seconds.
1800 parameters found in 128.9 seconds.
1900 parameters found in 136.0 seconds.
2000 parameters found in 144.5 seconds.
2100 parameters found in 151.2 seconds.
2200 parameters found in 159.1 seconds.
2300 parameters found in 166.6 seconds.
2400 parameters found in 174.0 seconds.
2500 parameters found in 181.4 seconds.
2600 parameters found i

In [ ]:
weights[m]

In [ ]:
values[m]

In [ ]:
limits[m]

In [ ]:
# UKP
weights, values, total_rewards = [], [], []
env = or_gym.make('Knapsack-v1')
count = 0
samples = 0
t0 = time.time()
while len(weights) < 5000:
    env.item_values = np.random.randint(0, 100, env.N)
    env.item_weights = np.random.randint(1, 100, env.N)
    env.item_limits_init = np.random.randint(0, 10, env.N)
    env.reset()
    # Solve IP
    model = build_bkp_ip_model(env)
    model, results = solve_math_program(model)
    # Solve with Heuristic
    heur_actions, heur_rewards = bkp_heuristic(env)
    
    tot_h_rewards = sum(heur_rewards)
    samples += 1
    if tot_h_rewards != model.obj.expr():
        weights.append(env.item_weights.copy())
        values.append(env.item_values.copy())
        total_rewards.append((model.obj.expr(), tot_h_rewards))
        count += 1
        if count % 100 == 0 and count > 0:
            print("{} parameters found in {:.1f} seconds.".format(count, time.time() - t0))
            
r = np.vstack(total_rewards).T
assert sum(r[0]>r[1]) == count
m = (r[0] - r[1]).argmax()
print("Max diff = {:.2f}%, sample_n = {}".format((1 - r[1, m]/r[0, m])*100, m))
print("Non-optimal rate: {:.2f}%".format(count/samples*100))

In [6]:
# Try new settings for weights and values
env = or_gym.make('Knapsack-v1')
env.item_values = np.random.randint(0, 100, env.N)
env.item_weights = np.random.randint(1, 100, env.N)
# env.item_values = np.array([15, 100, 90, 60, 40, 15, 10, 1])
# env.item_weights = np.array([2, 20, 20, 30, 40, 30, 60, 10])
# env.N = len(env.item_values)
# env.item_numbers = np.arange(env.N)
# env.max_weight = 102
env.item_limits_init = np.ones(env.N)
env.reset()

model = build_ukp_ip_model(env)
model, results = solve_math_program(model)
print("IP Objective: {:.2f}".format(model.obj.expr()))
_ = [print("x_i = {:.0f}_{}".format(model.x[x].value, i))
     for i, x in enumerate(model.x) if model.x[x].value != 0]
print("\t")
# Heuristic
heur_actions, heur_rewards = bkp_heuristic(env)
count = np.bincount(heur_actions)
action_count = count[count!=0]
actions = np.where(count!=0)
print("Heuristic Objective: {:.2f}".format(sum(heur_rewards)))
_ = [print("x_i = {:.0f}_{}".format(x, i))
     for x, i in zip(action_count, actions[0])]

print(env.current_weight)

IP Objective: 1700.00
x_i = 1_1
x_i = 1_9
x_i = 1_13
x_i = 1_17
x_i = 1_25
x_i = 1_32
x_i = 1_45
x_i = 1_54
x_i = 1_57
x_i = 1_79
x_i = 1_83
x_i = 1_88
x_i = 1_120
x_i = 1_127
x_i = 1_129
x_i = 1_146
x_i = 1_161
x_i = 1_165
x_i = 1_171
x_i = 1_177
x_i = 1_178
x_i = 1_190
x_i = 1_195
x_i = 1_197
	
Heuristic Objective: 1696.00
x_i = 1_1
x_i = 1_13
x_i = 1_17
x_i = 1_25
x_i = 1_32
x_i = 1_45
x_i = 1_54
x_i = 1_57
x_i = 1_79
x_i = 1_88
x_i = 1_120
x_i = 1_127
x_i = 1_129
x_i = 1_146
x_i = 1_150
x_i = 1_161
x_i = 1_163
x_i = 1_165
x_i = 1_171
x_i = 1_177
x_i = 1_178
x_i = 1_190
x_i = 1_195
x_i = 1_197
199


In [27]:
env.item_limits

array([0., 1., 1., 1., 1., 1., 1., 1.])

In [11]:
heur_actions

[0, 0]

In [12]:
env.reset()

{'action_mask': array([1, 1, 1, 1, 1, 1, 1, 1]),
 'avail_actions': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'state': array([[  2.,  20.,  20.,  30.,  40.,  30.,  60.,  10., 102.],
        [ 15., 100.,  90.,  60.,  40.,  15.,  10.,   1.,   0.],
        [  1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   0.]])}

In [22]:
vw_ratio = env.item_values / env.item_weights
vw_order = env.item_numbers[np.argsort(vw_ratio)[::-1]]
actions, rewards = [], []
done = False
while not done:
    max_item = vw_order[0]
    cont_flag = False
    if env.item_limits[max_item] == 0:
        # Remove item from list
        vw_order = vw_order[1:].copy()
        cont_flag = True
    elif env.item_weights[max_item] > (env.max_weight - env.current_weight):
        # Remove item from list
        vw_order = vw_order[1:].copy()
        cont_flag = True
    if len(vw_order) == 0:
        # End episode
        break
    if cont_flag:
        # Item doesn't fit or exist, start over
        continue
    state, reward, done, _ = env.step(max_item)
    actions.append(max_item)
    rewards.append(reward)

In [24]:
sum(rewards)

265

In [20]:
env.item_values

array([ 15, 100,  90,  60,  40,  15,  10,   1])

In [21]:
env.item_weights

array([ 2, 20, 20, 30, 40, 30, 60, 10])